---

- name: check if default config exists for nginx
  local_action: stat path="/etc/nginx/sites-enabled/default"
  register: nginx_result

- name: Create sites-disabled directory
  file:
    state: directory
    path: /etc/nginx/sites-disabled

- name: Move default file to sites-disabled
  command: mv /etc/nginx/sites-enabled/default /etc/nginx/sites-disabled/default
  when: nginx_result.stat.exists

- name: copy wiki config template
  template: src=wiki.conf.j2
    dest=/etc/nginx/sites-enabled/wiki.conf
  notify:
  - Restart nginx
