---

- name: Install MySQL
  apt: name={{ item }}
    update_cache=yes
    cache_valid_time=3600
    state=present
  become: root
  with_items:
  - python-mysqldb
  - mysql-server

- name: Ensure the MySQL service is started
  become: root
  service:
    name: mysql
    state: started
    enabled: true
