---
# requirements based on https://en.help.bluespice.com/wiki/Setup:Installation_Manual/MediaWiki/Installation

- name: install php
  apt: >
    name={{ item }}
    state=latest
    update_cache=no
  with_items:
    - imagemagick
    - php
    - php-curl
    - php-gd
    - php-tidy
    - php-mysql
    - libapache2-mod-php
    - php-xml
    - php-mbstring

- name: setup phpenmod mbstring
  become: root
  command: "phpenmod mbstring"

- name: setup phpenmod xml
  become: root
  command: "phpenmod xml"

- name: Restart Apache2
  service:
    name: apache2
    state: restarted

- lineinfile:
    dest: /etc/php/7.0/apache2/php.ini
    regexp: '^upload_max_filesize ='
    line: 'upload_max_filesize = 20M'

- lineinfile:
    dest: /etc/php/7.0/apache2/php.ini
    regexp: '^memory_limit = '
    line: 'memory_limit = 512M'

- lineinfile:
    dest: /etc/php/7.0/apache2/php.ini
    regexp: '^max_execution_time = '
    line: 'max_execution_time = 120'
