---

- name: check if mediawiki-bluespice has already been downloaded
  local_action: stat path="/tmp/BlueSpice-free-{{ bluespice.version }}-installer.zip"
  register: bluespice_result

- name: download mediawiki-bluespice from sourceforge
  get_url: url=http://ncu.dl.sourceforge.net/project/bluespice/BlueSpice-free-{{ bluespice.version }}-installer.zip
    dest=/tmp
  when: bluespice_result.stat.exists == False

- name: Creates directory
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Unarchive MediaWiki
  unarchive: src=/tmp/BlueSpice-free-{{ bluespice.version }}-installer.zip
    dest={{ server.root_directory }}
    copy=no
